In [2]:
import pandas as pd

data = {
    "Study_Hours": [2, 3, 4, 5, 6, 7, 8, 9, 1, 3, 5, 6, 7, 8, 4],
    "Attendance": [60, 65, 70, 75, 80, 85, 90, 95, 55, 68, 78, 82, 88, 92, 72],
    "Previous_Score": [45, 50, 55, 60, 65, 70, 75, 80, 40, 52, 62, 68, 73, 78, 58],
    "Assignments_Completed": [4, 5, 6, 7, 8, 9, 10, 10, 3, 5, 7, 8, 9, 10, 6],
    "Final_Score": [48, 52, 58, 63, 68, 74, 80, 85, 42, 55, 65, 70, 76, 82, 61]
}

df = pd.DataFrame(data)
df.to_csv("student_performance.csv", index=False)
print("Dataset created successfully!")
print(df)

Dataset created successfully!
    Study_Hours  Attendance  Previous_Score  Assignments_Completed  \
0             2          60              45                      4
1             3          65              50                      5
2             4          70              55                      6
3             5          75              60                      7
4             6          80              65                      8
5             7          85              70                      9
6             8          90              75                     10
7             9          95              80                     10
8             1          55              40                      3
9             3          68              52                      5
10            5          78              62                      7
11            6          82              68                      8
12            7          88              73                      9
13            8          92              78                     10
14            4          72              58                      6

    Final_Score
0            48
1            52
2            58
3            63
4            68
5            74
6            80
7            85
8            42
9            55
10           65
11           70
12           76
13           82
14           61

In [4]:
print("First 5 rows:")
display(df.head())
print("\nDataset shape:")
print(df.shape)
print("\nColumn names:")
print(df.columns)
print("\nDataset information:")
df.info()

First 5 rows:

   Study_Hours  Attendance  Previous_Score  Assignments_Completed  Final_Score
0            2          60              45                      4           48
1            3          65              50                      5           52
2            4          70              55                      6           58
3            5          75              60                      7           63
4            6          80              65                      8           68

Dataset shape:
(15, 5)

Column names:
Index(['Study_Hours', 'Attendance', 'Previous_Score', 'Assignments_Completed',
       'Final_Score'],
      dtype='object')

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Study_Hours            15 non-null     int64
 1   Attendance             15 non-null     int64
 2   Previous_Score         15 non-null     int64
 3   Assignments_Completed  15 non-null     int64
 4   Final_Score            15 non-null     int64
dtypes: int64(5)
memory usage: 732.0 bytes

In [5]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Study_Hours              0
Attendance               0
Previous_Score           0
Assignments_Completed    0
Final_Score              0
dtype: int64

In [7]:
X = df.drop("Final_Score", axis=1)
y = df["Final_Score"]

print("Features (X):")
print(X)
print("\nTarget (y):")
print(y)

Features (X):
    Study_Hours  Attendance  Previous_Score  Assignments_Completed
0             2          60              45                      4
1             3          65              50                      5
2             4          70              55                      6
3             5          75              60                      7
4             6          80              65                      8
5             7          85              70                      9
6             8          90              75                     10
7             9          95              80                     10
8             1          55              40                      3
9             3          68              52                      5
10            5          78              62                      7
11            6          82              68                      8
12            7          88              73                      9
13            8          92              78                     10
14            4          72              58                      6

Target (y):
0     48
1     52
2     58
3     63
4     68
5     74
6     80
7     85
8     42
9     55
10    65
11    70
12    76
13    82
14    61
Name: Final_Score, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (12, 4)
Testing data: (3, 4)

In [10]:
from sklearn.tree import DecisionTreeRegressor # Create the Decision Tree model decision_tree = DecisionTreeRegressor(random_state=42) # Train the model decision_tree.fit(X_train, y_train) print("Decision Tree model trained successfully!")

In [12]:
from sklearn.tree import DecisionTreeRegressor

# Re-initialize and train the model because the previous cell had inline comment syntax errors
decision_tree = DecisionTreeRegressor(random_state=42)
decision_tree.fit(X_train, y_train)

y_pred_dt = decision_tree.predict(X_test)

print("Actual Final Scores:")
print(y_test.values)
print("\nPredicted Final Scores:")
print(y_pred_dt)

Actual Final Scores:
[55 70 48]

Predicted Final Scores:
[52. 68. 42.]

In [14]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae_dt = mean_absolute_error(y_test, y_pred_dt)
mse_dt = mean_squared_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test, y_pred_dt)

print("Decision Tree Performance")
print("-------------------------")
print("MAE:", mae_dt)
print("MSE:", mse_dt)
print("R2 Score:", r2_dt)

Decision Tree Performance
-------------------------
MAE: 3.6666666666666665
MSE: 16.333333333333332
R2 Score: 0.8060686015831134

In [18]:
from sklearn.ensemble import RandomForestRegressor

# Create the Random Forest model
random_forest = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
random_forest.fit(X_train, y_train)
print("Random Forest model trained successfully!")

Random Forest model trained successfully!

In [19]:
y_pred_rf = random_forest.predict(X_test)
print("Actual Final Scores:")
print(y_test.values)
print("\nRandom Forest Predicted Final Scores:")
print(y_pred_rf)

Actual Final Scores:
[55 70 48]

Random Forest Predicted Final Scores:
[55.25 68.76 45.62]

In [21]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae_rf = mean_absolute_error(y_test, y_pred_rf)
mse_rf = mean_squared_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print("Random Forest Performance")
print("-------------------------")
print("MAE:", mae_rf)
print("MSE:", mse_rf)
print("R2 Score:", r2_rf)

Random Forest Performance
-------------------------
MAE: 1.2899999999999991
MSE: 2.4215
R2 Score: 0.9712486807387862

In [24]:
from sklearn.tree import DecisionTreeRegressor

# Create the Regression Tree model
regression_tree = DecisionTreeRegressor(max_depth=3, random_state=42)

# Train the model
regression_tree.fit(X_train, y_train)
print("Regression Tree model trained successfully!")

Regression Tree model trained successfully!

In [25]:
y_pred_rt = regression_tree.predict(X_test)
print("Actual Final Scores:")
print(y_test.values)
print("\nRegression Tree Predicted Final Scores:")
print(y_pred_rt)

Actual Final Scores:
[55 70 48]

Regression Tree Predicted Final Scores:
[52.         65.33333333 42.        ]

In [27]:
mae_rt = mean_absolute_error(y_test, y_pred_rt)
mse_rt = mean_squared_error(y_test, y_pred_rt)
r2_rt = r2_score(y_test, y_pred_rt)

print("Regression Tree Performance")
print("---------------------------")
print("MAE:", mae_rt)
print("MSE:", mse_rt)
print("R2 Score:", r2_rt)

Regression Tree Performance
---------------------------
MAE: 4.555555555555557
MSE: 22.259259259259277
R2 Score: 0.7357080035180297

In [29]:
comparison = pd.DataFrame({
    "Model": [ "Decision Tree", "Random Forest", "Regression Tree" ],
    "MAE": [ mae_dt, mae_rf, mae_rt ],
    "MSE": [ mse_dt, mse_rf, mse_rt ],
    "R2 Score": [ r2_dt, r2_rf, r2_rt ]
})

display(comparison)

             Model       MAE        MSE  R2 Score
0    Decision Tree  3.666667  16.333333  0.806069
1    Random Forest  1.290000   2.421500  0.971249
2  Regression Tree  4.555556  22.259259  0.735708

In [31]:
comparison = pd.DataFrame({
    "Model": [ "Decision Tree", "Random Forest", "Regression Tree" ],
    "MAE": [ mae_dt, mae_rf, mae_rt ],
    "MSE": [ mse_dt, mse_rf, mse_rt ],
    "R2 Score": [ r2_dt, r2_rf, r2_rt ]
})

display(comparison)

             Model       MAE        MSE  R2 Score
0    Decision Tree  3.666667  16.333333  0.806069
1    Random Forest  1.290000   2.421500  0.971249
2  Regression Tree  4.555556  22.259259  0.735708